### ISSUE TITLE
AttributeError: 'Distribution' object has no attribute 'convert_2to3_doctests' in Python 3.9 and Windows 10

### ISSUE THREAD

**Issue by kbatsuren** [rspeer/langcodes#44]
The environment setup is as follows:
The operating system - Windows 10.
Python version - 3.9.6
Pip version - pip 21.2.4 from C:\ProgramData\Miniconda3\lib\site-packages\pip (python 3.9)
Terminal command - pip install langcodes[data]

During the first installation, it throws the following error:

```
ERROR: Command errored out with exit status 1:
   command: 'C:\ProgramData\Miniconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\NUM\\AppData\\Local\\Temp\\pip-install-4ppckwvi\\language-data_d7af6b72ebe74a9db4472d299a899d42\\setup.py'"'"'; __file__='"'"'C:\\Users\\NUM\\AppData\\Local\\Temp\\pip-install-4ppckwvi\\language-data_d7af6b72ebe74a9db4472d299a899d42\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\NUM\AppData\Local\Temp\pip-wheel-b1_103om'
       cwd: C:\Users\NUM\AppData\Local\Temp\pip-install-4ppckwvi\language-data_d7af6b72ebe74a9db4472d299a899d42\
  Complete output (54 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\language_data
  copying language_data\build_data.py -> build\lib\language_data
  copying language_data\language_lists.py -> build\lib\language_data
  copying language_data\names.py -> build\lib\language_data
  copying language_data\name_data.py -> build\lib\language_data
  copying language_data\population_data.py -> build\lib\language_data
  copying language_data\registry_parser.py -> build\lib\language_data
  copying language_data\util.py -> build\lib\language_data
  copying language_data\__init__.py -> build\lib\language_data
  running egg_info
  writing language_data.egg-info\PKG-INFO
  writing dependency_links to language_data.egg-info\dependency_links.txt
  writing requirements to language_data.egg-info\requires.txt
  writing top-level names to language_data.egg-info\top_level.txt
  reading manifest file 'language_data.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  no previously-included directories found matching 'language_data\data\cldr-localenames-*'
  writing manifest file 'language_data.egg-info\SOURCES.txt'
  creating build\lib\language_data\data
  copying language_data\data\extra_language_names.csv -> build\lib\language_data\data
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\NUM\AppData\Local\Temp\pip-install-4ppckwvi\language-data_d7af6b72ebe74a9db4472d299a899d42\setup.py", line 20, in <module>
      setup(
    File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "C:\ProgramData\Miniconda3\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\ProgramData\Miniconda3\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\ProgramData\Miniconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\ProgramData\Miniconda3\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\ProgramData\Miniconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\ProgramData\Miniconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\ProgramData\Miniconda3\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\ProgramData\Miniconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\ProgramData\Miniconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools\command\build_py.py", line 55, in run
      self.build_package_data()
    File "C:\ProgramData\Miniconda3\lib\site-packages\setuptools\command\build_py.py", line 126, in build_package_data
      srcfile in self.distribution.convert_2to3_doctests):
  AttributeError: 'Distribution' object has no attribute 'convert_2to3_doctests'
```

**Comment by kbatsuren** [comment]
Please let me know what went wrong.

**Comment by rspeer** [comment]
I don't think this has anything to do with my code.

Might this be a bug in Miniconda's version of pip? Why is it running 2to3, and hasn't 2to3 been deprecated?

**Comment by kbatsuren** [comment]
Thank you very much for the idea and help. I am sure that it is related to Miniconda version :) I will update you soon and close this issue myself.
